### ISSUE TITLE
有一个问题，我在用nodejs上传的时候，cachedClient.createMultipartUpload报没有此方法

### ISSUE THREAD

**Issue by vincent-li** [berwin/aliyun-oss-upload-stream#19]
这是后台报错信息，代码就是拷贝你的，该怎么破！
/root/shield/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:144
    cachedClient.createMultipartUpload(details, function (err, data) {
                 ^

TypeError: cachedClient.createMultipartUpload is not a function
    at createMultipartUpload (/root/shield/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:144:18)
    at Writable.ws._write (/root/shield/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:115:7)
    at doWrite (_stream_writable.js:371:12)
    at writeOrBuffer (_stream_writable.js:357:5)
    at Writable.write (_stream_writable.js:274:11)
    at PNGStream.ondata (internal/streams/legacy.js:16:26)
    at emitTwo (events.js:125:13)
    at PNGStream.emit (events.js:213:7)
    at /root/shield/node_modules/canvas/lib/pngstream.js:48:14
    at /root/shield/node_modules/canvas/lib/pngstream.js:43:19
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickDomainCallback (internal/process/next_tick.js:198:9)

**Comment by berwin** [comment]
@vincent-li  传递的参数都对？

**Comment by berwin** [comment]
@vincent-li examples下的 client-to-server 这个例子在你的环境上能正确执行么？
