### ISSUE TITLE
cacheClient.createMultipartUpload error

### ISSUE THREAD

**Issue by jiangtao** [berwin/aliyun-oss-upload-stream#3]
``` bash
TypeError: Object [object Object] has no method 'createMultipartUpload'
    at createMultipartUpload (/Users/huangjiangtao/Places/Code/oss-upload/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:80:18)
    at Writable.ws._write (/Users/huangjiangtao/Places/Code/oss-upload/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:61:7)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Writable.write (_stream_writable.js:183:11)
    at write (_stream_readable.js:602:24)
    at flow (_stream_readable.js:611:7)
    at ReadStream.pipeOnReadable (_stream_readable.js:643:5)
    at ReadStream.emit (events.js:92:17)
    at emitReadable_ (_stream_readable.js:427:10)

```

**Comment by berwin** [comment]
@jtHwong 怎么使用的？

**Comment by berwin** [comment]
@jtHwong 会不会是使用方式不正确导致的？？？我在我这里测试过后没有发现你遇到的问题，没法把重现。你能详细的说一下这个问题是怎么出现的嘛？

**Comment by jiangtao** [comment]
就是直接把你的demo复制下来。直接使用的。`accessKeyId`,`secretAccessKey`,`endpoint`使用的自己的
node版本： 0.10.40 
npm版本： 3.7.5

**Comment by berwin** [comment]
@jtHwong 我在我这试过没发现问题。。aliyun-sdk 这个模块装的什么版本？？

**Comment by jiangtao** [comment]
@berwin  aliyun-sdk版本：  aliyun-sdk@1.8.2

**Comment by berwin** [comment]
@jtHwong 那不应该有问题，Bucket填的也正确？？

**Comment by jiangtao** [comment]
都是正确的， 从aliyun直接复制的。
我试试其他语言的包吧。

**Comment by berwin** [comment]
@jtHwong 你上传的是什么样的文件？能否发我一份？我试试。。email：berwin1995@qq.com

**Comment by jiangtao** [comment]
@berwin 好的 我把所有的代码给你一份 你把 accessKeyId,secretAccessKey,endpoint， bucket等改掉吧。

**Comment by berwin** [comment]
@jtHwong  好的~

**Comment by jiangtao** [comment]
已经发过来去了。麻烦你了。

**Comment by berwin** [comment]
@jtHwong  兄弟。。我看了一下，你用错了，ALI.OSS这个方法需要new一下，new完之后生成的实例当参数传入我的模块。

我建议你仔细看一下我README里的案例和examples中的demo~~

**Comment by jtHwong** [comment]
OK。。我在看下吧

**Comment by jtHwong** [comment]
你好， 能留个QQ，或者微信吗？我直接拿你的example改的。
