### ISSUE TITLE
Cannot read property 'Bucket' of null

### ISSUE THREAD

**Issue by cyenchen** [berwin/aliyun-oss-upload-stream#4]
按照例子上传图片返回这个错误

**Comment by cyenchen** [comment]
`var ossStream = require('aliyun-oss-upload-stream')(new ALY.OSS({
    accessKeyId: 'MzR2hreLo9w25lBo',
    secretAccessKey: 'AZKHfhPgUGfv3zU533zMalN2DgfR8Y',
    endpoint: 'http://axinjinfu.oss-cn-beijing.aliyuncs.com',
    apiVersion: '2013-10-15'
  }));
  var upload = ossStream.upload({
    Bucket: 'axinjinfu',
    Key: hat()
  });
  var read = fs.createReadStream('/home/evehehe/桌面/u=655038365,895076423&fm=21&gp=0.jpg');
  read.pipe(upload);
  upload = ossStream.upload({
    Bucket: 'axinjinfu',
    Key: hat()
  });`

**Comment by cyenchen** [comment]
`
var ossStream = require('aliyun-oss-upload-stream')(new ALY.OSS({
    accessKeyId: 'MzR2hreLo9w25lBo',
    secretAccessKey: 'AZKHfhPgUGfv3zU533zMalN2DgfR8Y',
    endpoint: 'http://axinjinfu.oss-cn-beijing.aliyuncs.com',
    apiVersion: '2013-10-15'
  }));
  var upload = ossStream.upload({
    Bucket: 'axinjinfu',
    Key: hat()
  });
  var read = fs.createReadStream('/home/evehehe/桌面/u=655038365,895076423&fm=21&gp=0.jpg');
  read.pipe(upload);
  upload = ossStream.upload({
    Bucket: 'axinjinfu',
    Key: hat()
  });
`

**Comment by berwin** [comment]
应该是参数传错了吧。。

**Comment by cyenchen** [comment]
这是代码:
var ossStream = require('aliyun-oss-upload-stream')(new ALY.OSS({
    accessKeyId: 'XXXXX',
    secretAccessKey: 'XXXXXXXXXXXXX',
    endpoint: 'XXXXXXXXXX',
    apiVersion: '2013-10-15'
  }));
  var upload = ossStream.upload({
    Bucket: 'axinjinfu',
    Key: hat()
  });
  var read = fs.createReadStream('/home/evehehe/桌面/u=655038365,895076423&fm=21&gp=0.jpg');
  read.pipe(upload);
  upload = ossStream.upload({
    Bucket: 'XXXXXXXXXX',
    Key: hat()
  });

**Comment by cyenchen** [comment]
代码:
var ossStream = require('aliyun-oss-upload-stream')(new ALY.OSS({
    accessKeyId: 'XXXXXXXXXXXXX',
    secretAccessKey: 'XXXXXXXXXXXXXXXXX',
    endpoint: 'XXXXXXXXXXXXXXXXXXXXXXXX',
    apiVersion: '2013-10-15'
  }));
  var upload = ossStream.upload({
    Bucket: 'XXXX',
    Key: hat()
  });
  var read = fs.createReadStream('/home/evehehe/桌面/u=655038365,895076423&fm=21&gp=0.jpg');
  read.pipe(upload);

**Comment by berwin** [comment]
你应该传递真实的Bucket，accessKeyId，secretAccessKey，endpoint，否则就会出现你刚刚的错误~

**Comment by cyenchen** [comment]
我是传的真实的

**Comment by berwin** [comment]
我刚刚试了一下，第一次是填一个错误的参数，然后报的错跟你的一模一样，然后我又试了一下正确的，然后上传成功。。。。。

**Comment by cyenchen** [comment]
我这边贴上网所以没有用真实的,在我这边都是用的真实的

**Comment by berwin** [comment]
噢噢。那你把错误信息帖全一下。我仔细瞧一瞧~~

**Comment by cyenchen** [comment]
错误信息
/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:99
      if (this._hardError) throw err;
                           ^

TypeError: Cannot read property 'Bucket' of null
    at abortUpload (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-oss-upload-stream/1.2.1/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:176:36)
    at Response.<anonymous> (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-oss-upload-stream/1.2.1/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:83:23)
    at Request.<anonymous> (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:163:20)
    at Request.callListeners (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/sequential_executor.js:113:20)
    at Request.emit (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:389:14)
    at Request.transition (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:52:12)
    at AcceptorStateMachine.runTo (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:17:12)
    at /home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:66:7)
    at AcceptorStateMachine.runTo (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:17:12)
    at /home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:66:7)
    at AcceptorStateMachine.runTo (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:17:12)
    at /home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:66:7)
    at AcceptorStateMachine.runTo (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:17:12)
    at /home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:66:7)
    at AcceptorStateMachine.runTo (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:17:12)
    at /home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:66:7)
    at AcceptorStateMachine.runTo (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:17:12)
    at /home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:29:10
    at Request.<anonymous> (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:58:9)
    at Request.<anonymous> (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/request.js:391:12)
    at Request.callListeners (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/sequential_executor.js:90:20)
    at Request.<anonymous> (/home/evehehe/code/hpt/node_modules/.npminstall/aliyun-sdk/1.8.5/aliyun-sdk/lib/sequential_executor.js:104:18)

**Comment by berwin** [comment]
建议你还是监察一下参数是否真的正确。。。或者信任我的话，可以把你的代码和Bucket等信息用邮件发我，我帮你监察一下。

**Comment by cyenchen** [comment]
var ossStream = require('aliyun-oss-upload-stream')(new ALY.OSS({
    accessKeyId: 'LhkQWQp7ACVwWyF3',
    secretAccessKey: '4uYAwAvlAi7JDRBg1nzy9MfYVxE7Mo',
    endpoint: 'http://testaxin.oss-cn-beijing.aliyuncs.com',
    apiVersion: '2013-10-15'
  }));
  var upload = ossStream.upload({
    Bucket: "testaxin",
    Key: 'asdf'
  });
  var read = fs.createReadStream('/home/evehehe/桌面/u=655038365,895076423&fm=21&gp=0.jpg');
  read.pipe(upload);

**Comment by cyenchen** [comment]
问题已经解决了,endpoint的时候把bucket带进去了

**Comment by berwin** [comment]
解决就好~~

**Comment by hfq-chenkeke** [comment]
没看明白

**Comment by berwin** [comment]
@hfq-chenkeke 就是参数传错了~ 哈哈哈哈
