### ISSUE TITLE
Cannot read property 'Bucket' of null

### ISSUE THREAD

**Issue by xingchch** [berwin/aliyun-oss-upload-stream#8]
正常情况下都不会出现这个错误,但是偶尔出出现以下错误. 并且这个错误也无法捕获, 直接导致node server 死机.    

```
/data/www/parser/node_modules/aliyun-sdk/lib/request.js:99
if (this._hardError) throw err;
                                 ^
TypeError: Cannot read property 'Bucket' of null
    at abortUpload (/data/www/parser/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:176:36)
    at Response.<anonymous> (/data/www/parser/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:83:23)
    at Request.<anonymous> (/data/www/parser/node_modules/aliyun-sdk/lib/request.js:163:20)
    at Request.callListeners (/data/www/parser/node_modules/aliyun-sdk/lib/sequential_executor.js:113:20)
    at Request.emit (/data/www/parser/node_modules/aliyun-sdk/lib/sequential_executor.js:81:10)
    at Request.emit (/data/www/parser/node_modules/aliyun-sdk/lib/request.js:389:14)
    at Request.transition (/data/www/parser/node_modules/aliyun-sdk/lib/request.js:52:12)
    at AcceptorStateMachine.runTo (/data/www/parser/node_modules/aliyun-sdk/lib/request.js:17:12)
    at /data/www/parser/node_modules/aliyun-sdk/lib/request.js:29:10
    at Request.transition (/data/www/parser/node_modules/aliyun-sdk/lib/request.js:66:7)

```

**Comment by berwin** [comment]
@xingchch  用的是哪个版本的aliyun-oss-upload-stream？

**Comment by berwin** [comment]
@xingchch 你可以试试更新下npm包试试，最新版本的是 1.2.2

**Comment by xingchch** [comment]
问题解决了．谢谢．

**Comment by xingchch** [comment]
1.node -v
　　v0.10.37
2.aliyun-oss-upload-stream@1.2.3 
└── aliyun-sdk@1.9.2 

我将一个字符串用以下方法上传到ｏｓｓ：

`var s = new stream.Readable();//"this is test";
　　s._read = function noop(){};
    s.push("this is test");
    s.push(null);
    s.pipe(upload);
`
但结果报错了：
/home/xxxxx/parser/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:85
var size = Buffer.byteLength(Buffer.concat(receivedBuffers, receivedBuffer
                      ^
TypeError: Argument must be a string
    at Writable.Client.upload.ws.end (/home/xxxxxx/node_modules/aliyun-oss-upload-stream/lib/aliyun-oss-upload-stream.js:85:23)
    at Readable.onend (_stream_readable.js:502:10)
    at Readable.g (events.js:180:16)
    at Readable.emit (events.js:92:17)
    at _stream_readable.js:944:16
    at process._tickDomainCallback (node.js:492:13)

Process finished with exit code 8
